name: hello-world
on: push
jobs:
    my-job:
       runs-on: ubuntu-latest
       steps:
          - name: my-step
            run: echo "hello world!"
          - name: my-world
            run: echo "hareesh"
          - name: my-roll
            run: echo "24cb013"
